"""empty message

Revision ID: 1b43d43211fd
Revises: 
Create Date: 2020-03-01 15:27:53.669683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b43d43211fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=40), nullable=False),
    sa.Column('email', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('company_name', sa.String(length=30), nullable=False),
    sa.Column('area_of_business', sa.String(length=40), nullable=False),
    sa.Column('office_address', sa.String(length=40), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('company_role', sa.String(length=20), nullable=False),
    sa.Column('num_employees', sa.Integer(), nullable=False),
    sa.Column('num_departments', sa.Integer(), nullable=False),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results_data')
    op.drop_table('admin')
    # ### end Alembic commands ###
