"""empty message

Revision ID: 85d147190e57
Revises: 9c04a8efbadd
Create Date: 2020-03-03 13:55:19.497996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d147190e57'
down_revision = '9c04a8efbadd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', 'email',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin', 'email',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    # ### end Alembic commands ###
